[package]
name = "runner"
version = "0.3.0"
edition = "2021"

[dependencies]
async-std = "1.10"
chrono = "0.4"
circular-queue = "0.2"
clap = "2.33"
futures = "0.3"
serde_json = "1.0"
subprocess = "0.2"
termion = "1.5"
tui = "0.16"
